"""a="my name is";
print(a);
print(a[:]);
print(a[0:]);
print(a[:5]);
print(a[0:5:2]);
print(a[0:5:3]);
print(a[::-1]);
print(a[-4:-2]);
print(a[-3:-1:-2])
print(a.lower());
print(a.isalnum());
print(a.isalpha());
print(a.endswith("is"));
print(a.upper());
print(a.capitalize());
print(a.count("i"));
print(a.replace("is","sa"));
print(a);
print(len(a));
"""
lb=[1,2,3,"sachin"];
"""print(l);
print(l[0]);
print(l[0:2]);
print(l[0:2:2]);
print(l[::-1]);
l.reverse();
print(l);
l.sort();
print(l);
"""
for item in lb:
    print(item);

i=0;
while(i<3):
    print(i);
    i=i+1;